# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=120, null=True)),
                ('in_stock', models.IntegerField(default=20)),
                ('price', models.IntegerField(default=0)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=products_app.models.get_dir)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=products_app.models.get_dir)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=products_app.models.get_dir)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=products_app.models.get_dir)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=products_app.models.get_dir)),
                ('featured', models.BooleanField(default=False)),
                ('best_selling', models.BooleanField(default=False)),
                ('product_description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_category')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='individualproduct',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.ProductCategory'),
        ),
    ]
