# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_bkash_number',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AddField(
            model_name='order',
            name='order_reference',
            field=models.IntegerField(default=-1),
        ),
    ]
