# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_auto_20180708_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=True),
        ),
    ]
