# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0003_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
