# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0007_auto_20180708_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(default=-1),
        ),
    ]
