# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0009_auto_20180714_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
    ]
