# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0010_remove_order_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_number',
            field=models.CharField(default=-1, max_length=10),
        ),
    ]
