# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0011_order_transaction_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_number',
        ),
        migrations.AddField(
            model_name='billingprofilemodel',
            name='transaction_number',
            field=models.CharField(default=-1, max_length=10),
        ),
    ]
