# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0013_auto_20180714_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
