# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0014_order_transaction_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofilemodel',
            name='transaction_number',
        ),
    ]
